### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#1]
## Important
- [ ] FocusScope — #20, commit be7bb90ba227dbceb54be9fdded94f25ca5d2103
- [ ] ListView
- [x] Loader — #247, merged as f255735e81e738f691028677a9c57996f2612588
- [x] WebSocket
- [ ] Screen
## Animations
- [ ] ColorAnimation
- [ ] OpacityAnimation
- [ ] XAnimation
- [ ] YAnimation
## Animators
- [ ] OpacityAnimator
- [ ] XAnimator
- [ ] YAnimator
## QtQuick.Layouts
- [ ] ColumnLayout
- [ ] RowLayout
- [ ] GridLayout
- [ ] Layout
## Other
- [ ] XmlListModel, XmlRole — #20, commits 22d307a, 5c90a47, e25251f. Needs restructuring and minor rewrite.
- [ ] Canvas

**Comment by igosoft** [comment]
Loader has been implemented. At least major feature works well.  If I'm not wrong Anton will merge soon my changes.

**Comment by igosoft** [comment]
May you please add ListView to "important" section ?

**Comment by ChALkeR** [comment]
@igosoft 
> May you please add ListView to "important" section ?

Added.

> Loader has been implemented. At least major feature works well. If I'm not wrong Anton will merge soon my changes.

The list represents the state of the master branch, once the relevant commits will get merged and tested, I will mark it as not missing anymore. Thanks! =)

**Comment by Plaristote** [comment]
If we can discuss here of what we'd like to have for the 1.0.0 version, I think it would be essential to work on those elements:
- FocusScope (and this may mean we'll have to rewrite Focus, I'm not sure it behaves as it should... point is, it's inherited by many elements, especially in QtQuick.Controls, we'll need it before going any further),
- Everything from QtQuick.Layouts (ColumnLayout, RowLayout, GridLayout and Layout), for similar reasons (QtQuick.Controls won't be of much use without layouts).

**Comment by ChALkeR** [comment]
@Plaristote FocusScope is awaiting rewrite and merge at be7bb90ba227dbceb54be9fdded94f25ca5d2103.

I updated the list, thanks!

**Comment by henrikrudstrom** [comment]
* ListItem has a lot of missing functionality (#112)
* [DelegateModel](http://doc.qt.io/qt-5/qml-qtqml-models-delegatemodel.html)
* [VisualItemModel](http://doc.qt.io/qt-4.8/qml-visualitemmodel.html)

**Comment by henrikrudstrom** [comment]
Also noticed @pavelvasev has a project https://github.com/pavelvasev/qmlweb.components, seems to implement a lot of QtQuick.Controls. 
@pavelvasev what is the state of this?

**Comment by pavelvasev** [comment]
Yes, these all are working good, I use it in my projects.
07.03.2016 17:12 пользователь "henrik" <notifications@github.com> написал:

**Comment by ChALkeR** [comment]
Migrated this list to https://github.com/qmlweb/qmlweb/projects/1.
