### ISSUE TITLE
Short-term plan

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#134]
I've updated the [milestones](https://github.com/qmlweb/qmlweb/milestones), those were pretty unsorted.

Atm, the new short-term plan is:
 - [x] [v0.1.0](https://github.com/qmlweb/qmlweb/milestones/0.1.0) — merge all the things.
 - [x] [v0.2.0](https://github.com/qmlweb/qmlweb/milestones/0.2.0) — initial cleanup.
 - [ ] [v0.3.0](https://github.com/qmlweb/qmlweb/milestones/0.3.0) — some extra features and fixes, perhaps. We should make it more compatible with Qt QML.
 - [ ] [v0.4.0](https://github.com/qmlweb/qmlweb/milestones/0.4.0) — some optimizations and benchmarks?

/cc @qmlweb/collaborators, please comment here if you have any proposals or objections =).

**Comment by Plaristote** [comment]
v0.2.0 should also bring us to the nodejs world, I believe. That's the first thing to do once the merge are done, IMO.

**Comment by henrikrudstrom** [comment]
good initiative, added #143 to 0.2.0, #126 to 0.3.0 as a proposal

**Comment by ChALkeR** [comment]
I added optimizations and benchmarks to v0.4.0 on the roadmap. /cc @pavelvasev, @igosoft

**Comment by ChALkeR** [comment]
I'm going to close this, as the post 0.2.0 issues are more or less like «fix everything and increase support», and there is no much sense in ratelimiting the minor releases for those.

The roadmap is now managed in [milestones](https://github.com/qmlweb/qmlweb/milestones).
Feel free to continue the discussion here and/or reopen, if needed.
