### ISSUE TITLE
Merge forks

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#15]
Atm, these GitHub forks are not merged yet:
- [x] @labsin — #16,
- [ ] @arnopaehler — #17,
- [x] @henrikrudstrom — #18,
- [ ] @pavelvasev — #32.

Also, I should check what was going on on the KDE repo (by @akreuzkamp):
- [ ] master branch ([original](https://quickgit.kde.org/?p=qmlweb.git)) — #19,
- [ ] realInheritance branch ([original](https://quickgit.kde.org/?p=qmlweb.git&a=shortlog&h=realInheritance)) — #20.

Also, one commit from KDE reviewboard (by @shry15harsh):
- [ ] Add property 'pressedButtons' to MouseArea — #49.

Also, one __huge__ commit from KDE Phabricator (by @igosoft):
- [ ] Merge igosoft-patches — #62.

**Comment by ChALkeR** [comment]
@labsin fork:
- [ ] 7080bd5 Fix gulpfile to do qt task before qt.min
- [ ] 46ad080 Remove libs from repo
- [ ] f7b9791 Fix component context
- [ ] daea9af Resemble more like qt5 modules
- [ ] d5d7248 Implement QMLColor
- [ ] 1c200b2 Change QMLProperty value constructor to object
- [ ] 0be9fc1 Fix nodejs with uglify2 in browser
- [ ] 8f80b5a Fix pre-parse example including qt.js and qt.min.js

**Comment by ChALkeR** [comment]
@labsin fork
--
- [x] 7080bd5 Fix gulpfile to do qt task before qt.min — **Merged**
- [x] 46ad080 Remove libs from repo — **Rejected,** libs will be kept in the repo for bower.
- [ ] f7b9791 Fix component context
- [ ] daea9af Resemble more like qt5 modules
- [ ] d5d7248 Implement QMLColor
- [ ] 1c200b2 Change QMLProperty value constructor to object
- [ ] 0be9fc1 Fix nodejs with uglify2 in browser
- [ ] 8f80b5a Fix pre-parse example including qt.js and qt.min.js

@henrikrudstrom fork
--
TODO

@arnopaehler fork
--
TODO

kde/master branch
--
TODO

kde/realInheritance branch:
--
TODO

**Comment by ChALkeR** [comment]
There is now a [merge](https://github.com/qmlweb/qmlweb/labels/merge) label and [0.1.0](https://github.com/qmlweb/qmlweb/milestones/0.1.0) milestone.

No reason for keeping the meta issue.
