### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#22]
Note: these should be treated as an incomplete list of blockers, for example everything listed here for 0.4.0 could be actually done by the 0.2.0 release, and that would not be something bad.

## 0.1.0
- [ ] Merge as much as possible, see #15.

## 0.2.0
- [ ] Make this usable under Node.js, see #41.
- [x] Revive the gulp plugin (in a separate repo).

## 0.3.0
- [ ] Merge everything else, see #15.
- [ ] Enable eslint, see #21.

## 0.4.0
- [x] Fix tests, #6.
- [ ] Actually add some tests.
- [x] Travis tests, #7.

## 1.0.0
- [ ] Revive examples
- [ ] Implement more elements, see #1

**Comment by Plaristote** [comment]
The gulp plugin is alive again, at https://github.com/qmlweb/gulp-qmlweb

**Comment by ChALkeR** [comment]
Yay!

**Comment by ChALkeR** [comment]
I'm splitting this issues into proper GitHub roadmap, and I won't support this list anymore.
