### ISSUE TITLE
Merge remaining @igosoft patches

### ISSUE THREAD

**Issue by ChALkeR** [qmlweb/qmlweb#223]
These are the remaining @igosoft patches.

This is a complete list of individual patches that sum up to the original patch by @igosoft.
It replaces both #128 and #62.

Note that the order might be not correct, and some patches that are closer to the bottom could require some patched that are closer to the top (and other way around).

 - [x] c819a71 Rebuild ./lib — **Rejected**.
 - [x] 71eb280 src/uglify: Make three constants local — **Rejected**.
 - [x] 566df0c Replace eval with new Function in import.js — **Rejected**.
 - [x] a483a33 parser.js: Add "string" and "num" — **Rejected**.
 - [x] aa0a3f4 Change Item overflow style from "hidden" to "auto" — **Rejected**.
 - [x] 24c3ae4 Add some unused commented out code — **Rejected**.
 - [x] 41e7621 unset item.parent inside $delete $tidyupList — **Rejected**.
 - [x] 85d3f04 Code style changes and microoptimization — **Rejected**.
 - [x] fb6d78b Unwanted Loader changes (mostly style) — **Rejected**.
 - [x] 6b018eb Unwanted changes and microptimizations — **Rejected**.
 - [x] 15265a9 Some code structuring in ListModel — **Rejected**.
 - [x] 6c9d44a QMLPositioner: bind to implicit size changes — **Rejected** in #219.
 - [x] f507944 Repeater updates — **Merged** in #248.
 - [x] 691330f ListModel updates — **Merged** in #242.
 - [x] 46c6f2a Finalize QMLComponent imports in QML Object constructor — **Postponed** in #246.
 - [x] 2308bcc move default property updates to the top in applyProperties — **Merged** in #225.
 - [x] 31afc1f Item parent fixes — **Postponed** in #245.
 - [x] af7f263 Remove this.dom.qml property — **Merged** in #224.
 - [x] cc4a8db Positioners implicit size fixes — **Discarded** by @igosoft, comments inside.
 - [x] 6b7593a Update Loader — **Merged** in #247.
 - [x] d6dfbeb Context fixes — **Postponed** in #244. Some changes already addressed by c13919e.
 - [x] f46c60c Property binding fixes — **Discarded** by @igosoft, comments inside.
 - [x] f6c9c6d Text: unify implicit size updates, minor fixes — **Merged** in fbe7c26d68.
 - [x] 50c9d8e Do not perform layoutChildren for empty positioners — **Rejected** in #221.
 - [x] c7c65ef QMLEngine: return component from loadFile() and loadQMLTree() — **Merged** in #218.
 - [x] 3f2354f QMLEngine: allow to specify parentComponent in loadQMLTree — **Merged** in #193.
 - [x] 51030d8 Do not return values from property setters — **Merged** in #220.
 - [x] 99d1da1 QMLPositioner: don't trigger layoutChildren on opacity changes — **Merged** in #217.
 - [x] ec1600c Do not hide zero-opacity items in positioners — **Merged** in #217.
 - [x] 03a2164 Import Loader from master — **Duplicate**.
 - [x] 42826cf Added childrenRect property — **Merged** in #172.
 - [x] df363a3 Added MouseArea cursorShape property — **Merged** in #172.
 - [x] 1d1637e Added ScrollView — **Merged** in #172.
 - [x] 365d304 Added Screen — **Duplicate**.
 - [x] a78bec0 Added ComboBox — **Duplicate**.
 - [x] 11b6bfd Item: this.dom.style -> this.css — **Merged** in #122.
 - [x] 6a600ca Flow: use Flow.LeftToRight constant instead of 0 where applicable — **Merged** in #122.
 - [x] 7863a7e TextInput: fix dom style — **Merged** in #122.
 - [x] 07b5256 Log errors on failed connections — **Merged** in #122.
 - [x] 0652d0a Log errors on failed qml file loads — **Merged** in #122.
 - [x] 38dbc12 Moved Button to QtQuick.Controls — **Merged** in #122.
 - [x] f06cbc4 Add QtObject — **Merged** in #122.
 - [x] 409a126 gitignore: Add .arcconfig — **Merged** in #122.

/cc @igosoft, @akreuzkamp, @Plaristote, @pavelvasev.

**Comment by ChALkeR** [comment]
Ok, all commits here are either sorted out or have open pull requests.

**Comment by ChALkeR** [comment]
I postponed the following commits:
 * 46c6f2a Finalize QMLComponent imports in QML Object constructor — **Postponed** in #246.
 * 31afc1f Item parent fixes — **Postponed** in #245.
 * d6dfbeb Context fixes — **Postponed** in #244. Some changes already addressed by c13919e.

Those introduce small code changes, but two of them break things and need to be looked at, and one of them was significantly changed by me, and also should be looked at.

Those should not block 0.1.0 release. Closing this issue, everything else here is merged.
